name: "Add comment if all assignees have commented"
on:
  issue_comment:
    types: 
      - created
  
jobs:
  primary:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Notify if all assignees have commented
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        LABEL: 'periodic-update'
        COMMENT: 'Looks like everyone has shared their inputs for the periodic update!'
