name: "Notify if everyone has added snippets"
on:
  issue_comment:
    types: 
      - created
  
jobs:
  primary:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Issue Assignees with Commenters
      uses: ./
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        LABEL: 'friday-snippets'
        COMMENT: 'Yippee! Looks like everyone has commented :sparkle: &nbsp; @mvkaran-sandbox Over to you! <br/> I will close this issue automatically on Monday.'